-- aka.workflow
-- Copyright (c) Akatsumekusa and contributors

------------------------------------------------------------------------------
-- Permission is hereby granted, free of charge, to any person obtaining a
-- copy of this software and associated documentation files (the "Software"),
-- to deal in the Software without restriction, including without limitation
-- the rights to use, copy, modify, merge, publish, distribute, sublicense,
-- and/or sell copies of the Software, and to permit persons to whom the
-- Software is furnished to do so, subject to the following conditions:

-- The above copyright notice and this permission notice shall be included in
-- all copies or substantial portions of the Software.

-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
-- FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
-- DEALINGS IN THE SOFTWARE.
------------------------------------------------------------------------------

------------------------------------------------------------------------------
-- Workflow register
-- A module need to have a workflow table in the root table:
-- ```
-- local functions = {}
-- functions.versioning = versioning
-- functions.workflow = workflow
-- return functions
-- ```
-- The workflow table:
-- ```
-- workflow = {
--     display_name = "BackupProto"
--
--     -- The main function
--     run = function(subs, sel, act, work, extra_data)
--         return sel, act, extra_data
--     end
--
--     -- If you are processing subtitles line by line, you should set both values to 1;
--     -- If, for example, you are doing gradient and you need lines to be grouped by 2, you should set both values to 2;
--     -- If you don't really know how many lines you should be feed with, you can set both values to 0;
--     max_lines_taken = 1 -- Setting this to 0 means inf
--     min_lines_taken = 1 -- Setting this to 0 is the same as 1
--
--     -- There are 4 possible values for multithreading
--     -- true if each line section is processed independent of each other and
--     --         YOU DON'T INSERT OR DELETE LINES FROM THE SUBTITLE OBJECT,
--     -- "aggressive" if you expect your process to be slower than 50 ms per line section and
--     --                 each line section is processed independent of each other and
--     --                 YOU DON'T INSERT OR DELETE LINES FROM THE SUBTITLE OBJECT
--     -- false if you multithreading is not possible (the line sections will still be fed one by one)
--     -- "manual" if you will need all the lines to be fed to you at once
--     multithreading = true
-- }
-- ```
------------------------------------------------------------------------------
-- Workflow table:
-- ```
-- {
--     ["runner"] = "aka.backup",
--     ["work"] = {}
--     ["flow"] = {}
-- }
-- ```
-- If flow is a table, the script specified by work will be called with the
-- table as config.
-- ```
-- {
--     ["worker"] = "aka.Backup",
--     ["work"] = "Work Name"
-- }
-- ```
-- If flow is a string, aka.workflow will read the workflow with the specified
-- name and the script specified by work will be called with the table read.
-- ```
-- {
-- }
-- ```
-- If the table doesn't have a work, it is a null workflow. Nothing will be
-- performed by no error will be raised either.
------------------------------------------------------------------------------
